import type { Category } from "./UnitData";

export type Alias = {
  category: Category;
  unit: string;
};
export const aliases: Record<string, { category: Category; unit: string }> = {
  meter: { category: "length", unit: "m" },
  meters: { category: "length", unit: "m" },
  metre: { category: "length", unit: "m" },
  metres: { category: "length", unit: "m" },
  kilometer: { category: "length", unit: "km" },
  kilometers: { category: "length", unit: "km" },
  kilometre: { category: "length", unit: "km" },
  kilometres: { category: "length", unit: "km" },
  centimeter: { category: "length", unit: "cm" },
  centimeters: { category: "length", unit: "cm" },
  millimeter: { category: "length", unit: "mm" },
  millimeters: { category: "length", unit: "mm" },
  inch: { category: "length", unit: "in" },
  inches: { category: "length", unit: "in" },
  feetandinches: { category: "length", unit: "ftin" },
  "feet and inches": { category: "length", unit: "ftin" },
  "inches and feet": { category: "length", unit: "ftin" },
  "inch and feet": { category: "length", unit: "ftin" },
  "inches and foot": { category: "length", unit: "ftin" },
  "inch and foot": { category: "length", unit: "ftin" },
  "inches & feet": { category: "length", unit: "ftin" },
  "inch & foot": { category: "length", unit: "ftin" },
   "feet & inches": { category: "length", unit: "ftin" },
  "in & ft": { category: "length", unit: "ftin" },
  "inch feet": { category: "length", unit: "ftin" },
  "inches foot": { category: "length", unit: "ftin" },
  "inch foot": { category: "length", unit: "ftin" },
  "in / ft": { category: "length", unit: "ftin" },
  "in-ft": { category: "length", unit: "ftin" },
  "in ft": { category: "length", unit: "ftin" },
  feetinch: { category: "length", unit: "ftin" },
  feetinches: { category: "length", unit: "ftin" },
  ftin: { category: "length", unit: "ftin" },
  ftandin: { category: "length", unit: "ftin" },
  inchesandfeet: { category: "length", unit: "ftin" },
  inchandfeet: { category: "length", unit: "ftin" },
  height: { category: "length", unit: "ftin" },
  foot: { category: "length", unit: "ft" },
  feet: { category: "length", unit: "ft" },
  yard: { category: "length", unit: "yd" },
  yards: { category: "length", unit: "yd" },
  mile: { category: "length", unit: "mi" },
  miles: { category: "length", unit: "mi" },
  nauticalmile: { category: "length", unit: "nmi" },
  nauticalmiles: { category: "length", unit: "nmi" },
  "nautical mile": { category: "length", unit: "nmi" },
  "nautical miles": { category: "length", unit: "nmi" },
  nmi: { category: "length", unit: "nmi" },
  nm: { category: "length", unit: "nmi" },

  g: { category: "mass", unit: "g" },
  gram: { category: "mass", unit: "g" },
  grams: { category: "mass", unit: "g" },
  gramme: { category: "mass", unit: "g" },
  grammes: { category: "mass", unit: "g" },
  grame: { category: "mass", unit: "g" },
  grames: { category: "mass", unit: "g" },
  miligram: { category: "mass", unit: "mg" },
  miligrams: { category: "mass", unit: "mg" },
  miligramme: { category: "mass", unit: "mg" },
  miligrammes: { category: "mass", unit: "mg" },
  miligrame: { category: "mass", unit: "mg" },
  miligrames: { category: "mass", unit: "mg" },
  mg: { category: "mass", unit: "mg" },
  mgr: { category: "mass", unit: "mg" },
  microgram: { category: "mass", unit: "µg" },
  micrograms: { category: "mass", unit: "µg" },
  microgramme: { category: "mass", unit: "µg" },
  microgrammes: { category: "mass", unit: "µg" },
  micrograme: { category: "mass", unit: "µg" },
  microgrames: { category: "mass", unit: "µg" },
  mcg: { category: "mass", unit: "µg" },
  μg: { category: "mass", unit: "µg" },
  ug: { category: "mass", unit: "µg" },
  kilo: { category: "mass", unit: "kg" },
  kilos: { category: "mass", unit: "kg" },
  kilogram: { category: "mass", unit: "kg" },
  kilograms: { category: "mass", unit: "kg" },
  kilograme: { category: "mass", unit: "kg" },
  kilogrames: { category: "mass", unit: "kg" },
  kilogramme: { category: "mass", unit: "kg" },
  kilogrammes: { category: "mass", unit: "kg" },
  pound: { category: "mass", unit: "lb" },
  pounds: { category: "mass", unit: "lb" },
  lbs: { category: "mass", unit: "lb" },
  ounce: { category: "mass", unit: "oz" },
  ounces: { category: "mass", unit: "oz" },
  stone: { category: "mass", unit: "st" },
  stones: { category: "mass", unit: "st" },
  ton: { category: "mass", unit: "t" },
  tons: { category: "mass", unit: "t" },
  tonne: { category: "mass", unit: "t" },
  tonnes: { category: "mass", unit: "t" },

  liter: { category: "volume", unit: "L" },
  liters: { category: "volume", unit: "L" },
  litre: { category: "volume", unit: "L" },
  litres: { category: "volume", unit: "L" },
  l: { category: "volume", unit: "L" },
  ml: { category: "volume", unit: "mL" },
  milliliter: { category: "volume", unit: "mL" },
  milliliters: { category: "volume", unit: "mL" },
  gl: { category: "volume", unit: "gal" },
  gal: { category: "volume", unit: "gal" },
  gallon: { category: "volume", unit: "gal" },
  gallons: { category: "volume", unit: "gal" },
  cups: { category: "volume", unit: "cup" },
  quart: { category: "volume", unit: "qt" },
  quarts: { category: "volume", unit: "qt" },
  pint: { category: "volume", unit: "pt" },
  pints: { category: "volume", unit: "pt" },
  tablespoon: { category: "volume", unit: "tbsp" },
  tablespoons: { category: "volume", unit: "tbsp" },
  teaspoon: { category: "volume", unit: "tsp" },
  teaspoons: { category: "volume", unit: "tsp" },

  kmh: { category: "speed", unit: "km/h" },
  kph: { category: "speed", unit: "km/h" },
  knots: { category: "speed", unit: "kt" },
  knot: { category: "speed", unit: "kt" },

  celsius: { category: "temperature", unit: "C" },
  c: { category: "temperature", unit: "C" },
  "°c": { category: "temperature", unit: "C" },
  fahrenheit: { category: "temperature", unit: "F" },
  f: { category: "temperature", unit: "F" },
  "°f": { category: "temperature", unit: "F" },
  kelvin: { category: "temperature", unit: "K" },
  k: { category: "temperature", unit: "K" },
  absolutezero: { category: "temperature", unit: "K" },
  "absolute zero": { category: "temperature", unit: "K" },
  kelvins: { category: "temperature", unit: "K" },
  gasmark: { category: "temperature", unit: "gasMark" },
  gasmarks: { category: "temperature", unit: "gasMark" },
  gas: { category: "temperature", unit: "gasMark" },
  "gas mark": { category: "temperature", unit: "gasMark" },
  "gas marks": { category: "temperature", unit: "gasMark" },
  "oven gas": { category: "temperature", unit: "gasMark" },
  "gas oven": { category: "temperature", unit: "gasMark" },
  "uk gas mark": { category: "temperature", unit: "gasMark" },
  gm: { category: "temperature", unit: "gasMark" },

  second: { category: "time", unit: "s" },
  seconds: { category: "time", unit: "s" },
  sec: { category: "time", unit: "s" },
  minute: { category: "time", unit: "min" },
  minutes: { category: "time", unit: "min" },
  mins: { category: "time", unit: "min" },
  hour: { category: "time", unit: "h" },
  hours: { category: "time", unit: "h" },
  hr: { category: "time", unit: "h" },
  hrs: { category: "time", unit: "h" },
  day: { category: "time", unit: "d" },
  days: { category: "time", unit: "d" },
  week: { category: "time", unit: "wk" },
  weeks: { category: "time", unit: "wk" },
  month: { category: "time", unit: "mo" },
  months: { category: "time", unit: "mo" },
  mo: { category: "time", unit: "mo" },
  mos: { category: "time", unit: "mo" },
  year: { category: "time", unit: "yr" },
  years: { category: "time", unit: "yr" },
};